[build]
  publish = "dist"
  command = "yarn build"
  edge_handlers = "src/edge-handlers"

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  edge_handlers = "onEvent"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200